package di

// container.go documents the provider graph wired in wire_gen.go.
//
// In the reference architecture (auth-service) this file holds the Google Wire
// provider set and wire_gen.go is generated by `make wire`. To keep this build
// dependency-free and runnable without the wire codegen tool, wire_gen.go is
// hand-authored to the same shape. When adding a new component:
//
//  1. Add its provider/constructor below (for documentation).
//  2. Construct it in InitializeApp (wire_gen.go) in dependency order.
//  3. If the HTTP layer needs it, expose an accessor on AppInterface (app-logic.go).
//
// Provider graph (leaf → root):
//
//	drivers:        NewPostgres(cfg.Store) → *gorm.DB
//	                NewRedis(cfg.Cache)    → *redis.Client
//
//	repositories:   NewExpenseRepository(db), NewAutoPayRepository(db),
//	                NewFinanceRepository(db)
//	                NewSummaryCache(rdb)
//
//	services:       NewTokenService(cfg.Token)                     ← verify-only
//	                NewExpenseService(expenseRepo)
//	                NewAutoPayService(autopayRepo, summaryCache)
//	                NewFinanceService(financeRepo, summaryCache)
//	                NewAnalyticsService(autopayRepo, financeSvc, summaryCache, ttl)
//
//	app:            &app{...} implementing AppInterface
const providerGraphDoc = "see container.go comment"

var _ = providerGraphDoc
