// wire_gen.go contains the dependency-injection wiring. In the reference
// architecture this file is generated by `make wire` from the provider set in
// container.go; here it is hand-authored but kept in the same shape — a single
// InitializeApp constructor that builds the object graph bottom-up.
//
// Edit container.go's provider notes and keep this in sync.
package di

import (
	"fmt"

	"github.com/kharchibook/expense-service/config"
	"github.com/kharchibook/expense-service/drivers"
	"github.com/kharchibook/expense-service/pkg/domain/service"
	whatsappsvc "github.com/kharchibook/expense-service/pkg/domain/service/whatsapp"
	"github.com/kharchibook/expense-service/pkg/infrastructure/authclient"
	"github.com/kharchibook/expense-service/pkg/infrastructure/cacherepo"
	"github.com/kharchibook/expense-service/pkg/infrastructure/msgqueuerepo"
	"github.com/kharchibook/expense-service/pkg/infrastructure/sqlrepo"
	"github.com/kharchibook/expense-service/pkg/infrastructure/whatsappclient"
	"github.com/kharchibook/expense-service/third_party/platlogger"
)

// InitializeApp builds the full application object graph from configuration.
func InitializeApp(cfg *config.Config) (AppInterface, error) {
	// --- drivers (external infrastructure) ---
	db, err := drivers.NewPostgres(cfg.Store)
	if err != nil {
		return nil, fmt.Errorf("init postgres: %w", err)
	}
	rdb, err := drivers.NewRedis(cfg.Cache)
	if err != nil {
		return nil, fmt.Errorf("init redis: %w", err)
	}

	// --- infrastructure repositories ---
	expenseRepo := sqlrepo.NewExpenseRepository(db)
	autopayRepo := sqlrepo.NewAutoPayRepository(db)
	financeRepo := sqlrepo.NewFinanceRepository(db)
	summaryCache := cacherepo.NewSummaryCache(rdb)

	// --- domain services (built bottom-up) ---
	tokenSvc, err := service.NewTokenService(cfg.Token)
	if err != nil {
		return nil, fmt.Errorf("init token service: %w", err)
	}
	expenseSvc := service.NewExpenseService(expenseRepo)
	autopaySvc := service.NewAutoPayService(autopayRepo, summaryCache)
	financeSvc := service.NewFinanceService(financeRepo, summaryCache)
	analyticsSvc := service.NewAnalyticsService(autopayRepo, financeSvc, summaryCache, cfg.Cache.SummaryTTL)

	// --- WhatsApp pipeline (inbound publisher + worker orchestrator) ---
	var publisher msgqueuerepo.IInboundPublisher
	if cfg.MsgQueue.Enabled {
		publisher, err = msgqueuerepo.NewKafkaPublisher(cfg.MsgQueue.Brokers, cfg.MsgQueue.InboundTopic, cfg.MsgQueue.DLQTopic)
		if err != nil {
			return nil, fmt.Errorf("init kafka publisher: %w", err)
		}
	} else {
		platlogger.Warn("MsgQueue disabled — using stub WhatsApp publisher (local dev)")
		publisher = msgqueuerepo.NewStubPublisher()
	}

	authClient := authclient.New(cfg.Auth.URL, cfg.Auth.InternalKey)
	sender := whatsappclient.New(cfg.WhatsApp)
	whatsappSvc := whatsappsvc.New(whatsappsvc.Deps{
		Auth:      authClient,
		Sender:    sender,
		Publisher: publisher,
		Redis:     rdb,
		Expenses:  expenseSvc,
		Autopays:  autopaySvc,
		Analytics: analyticsSvc,
		Finance:   financeSvc,
		SignupURL: cfg.WhatsApp.SignupURL,
	})

	return &app{
		cfg:          cfg,
		tokenSvc:     tokenSvc,
		expenseSvc:   expenseSvc,
		autopaySvc:   autopaySvc,
		financeSvc:   financeSvc,
		analyticsSvc: analyticsSvc,
		publisher:    publisher,
		whatsappSvc:  whatsappSvc,
		db:           db,
		rdb:          rdb,
	}, nil
}
